In [9]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

In [3]:
df = pd.read_csv('judge-1377884607_tweet_product_company.csv',encoding='latin1')
df.head()

,tweet_text,emotion_in_tweet_is_directed_at,is_there_an_emotion_directed_at_a_brand_or_product
0,.@wesley83 I have a 3G iPhone. After 3 hrs twe...,iPhone,Negative emotion
1,@jessedee Know about @fludapp ? Awesome iPad/i...,iPad or iPhone App,Positive emotion
2,@swonderlin Can not wait for #iPad 2 also. The...,iPad,Positive emotion
3,@sxsw I hope this year's festival isn't as cra...,iPad or iPhone App,Negative emotion
4,@sxtxstate great stuff on Fri #SXSW: Marissa M...,Google,Positive emotion

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9093 entries, 0 to 9092
Data columns (total 3 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   tweet_text                                          9092 non-null   object
 1   emotion_in_tweet_is_directed_at                     3291 non-null   object
 2   is_there_an_emotion_directed_at_a_brand_or_product  9093 non-null   object
dtypes: object(3)
memory usage: 213.2+ KB

In [5]:
df.describe()

,tweet_text,emotion_in_tweet_is_directed_at,is_there_an_emotion_directed_at_a_brand_or_product
count,9092,3291,9093
unique,9065,9,4
top,RT @mention Marissa Mayer: Google Will Connect...,iPad,No emotion toward brand or product
freq,5,946,5389

In [6]:
df['is_there_an_emotion_directed_at_a_brand_or_product'].unique()

array(['Negative emotion', 'Positive emotion',
       'No emotion toward brand or product', "I can't tell"], dtype=object)

When cleaning the text I want to do the following:
1. Remove any starting or trailing white spaces
2. Ensure every word is lower case
3. Remove any numbers
4. Remove any special characters
5. Remove any emojis (if they dont count as special characters)
6. Tokenize
7. Lemmertize
8. Remove any stopwords
9. Remove any words that repeat consecutively
10. remove any letters that repeat more than twice
11. Remove any word that is connected to the # symbol (any words connected to special symbols)
12. Remove any links they all look like this {link}
13. Remove any empty lines.
14. Remove any . symbols that repeat multiple times
15. Remove special symbols connected to numbers 5,000
16. Remove @gmail.com or @yahoo.com
17. Remove .com

In [11]:
stop_words = set(stopwords.words('english'))
# print(len(stop_words))

In [ ]:
#i am using the emoji library in python. i have installed it using pip install emoji
import emoji

def clean_text(text):
    # text = text.re.sub(r'#\w+','',text) #removing any hashtags
    # text = text.re.sub(r'@\w+','',text) #removing any mentions
    text = emoji.replace_emoji(text,replace='')
    text = text.re.sub(r'[#@]\w+') #removed both hashtags and tweets
    text = text.re.sub(r'https?=://\S+','',text) #this will remove any link that starts with https://
    text = text.re.sub(r'\{link\}','',text) #this will remove {link} from the text
    text= text.re.sub(r'a-zA-Z\s','',text) #remove anything that isn't an alphabetical letter
    text = text.re.sub(r'\s+','',text) #remove any white spaces that appear more than once
    text = text.re.sub(r'(\w)\1{3,}') #in order to remove letters that appear 3 or more times consecutively
    text = word_tokenize(text)

    text = [word.lower() for word in text if word.lower not in stop_words] #removing stopwords
    # text = [i in text if text not in stop_words] #we will have to define a set of stop words

In [6]:
haha  = [5,8,9,2,6,7]
# hello = []
# for i in range(1,11):
#     if i not in haha:
#         hello.append(i)
#         print(hello)

# print(hello)

hi = [ num for num in range(1,11) if num not in haha ]
print(hi)

[1, 3, 4, 10]